# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode7.3
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- pod install --project-directory=Example
# - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/VISPER-Redux.xcworkspace -scheme VISPER-Redux-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint  --swift-version=4.0
